version: '3'

services:

  freeim:
    build: .
    container_name: freeim
    ports:
      - "8080:8080"
      - "9001:9001"
    volumes:
      - ./development.yml:/development.yml
    command: server